[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True

[mypy-mariadb.*]
ignore_missing_imports = True

[mypy-flask.*]
ignore_missing_imports = True

[mypy-werkzeug.utils]
ignore_missing_imports = True

[mypy-dotenv.*]
ignore_missing_imports = True

[mypy-requests.utils]
ignore_missing_imports = True
